apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-s3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sdtitecnologi/minio-rancher-argocd
    targetRevision: HEAD
    path: apps/csi-s3
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
