apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-s3-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sdtitecnologi/minio-rancher-argocd
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      include: "**/application.yaml"
      exclude: "**/kustomization.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
