apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: minio
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: "*"
    helm:
      values: |
        auth:
          rootUser: minioadmin
          rootPassword: minioadmin
        persistence:
          enabled: true
          size: 100Gi
        service:
          type: LoadBalancer
        # Descomente para usar Ingress:
        # ingress:
        #   enabled: true
        #   hostname: minio.example.com
        #   path: /
        #   tls: true
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
